[package]
name = "nature"
version = "0.6.0"
authors = ["XueBin Li <llxxbb@yeah.net>"]
edition = "2018"
description = "Nature is a data-driven, business-oriented, decentralized platform for building big system."
repository = "https://github.com/llxxbb/Nature"
readme = "README.md"
license = "MIT"
keywords = ["FaaS", "MQ", "BPM", "Gateway", "Workflow"]

[dependencies]
# normal
chrono = { version = "0.4", features = ["serde"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.4"
uuid = { version = "0.8", features = ["v3"] }
lru_time_cache = "0.10"
futures = "0.3"

# for local executor implement
libloading = "0.5"


# log
log = "0.4"
fern = "0.6"        # Simple, efficient logging

#config
dotenv = "0.15"

# web
reqwest = { version = "0.10", features = ["blocking","json"] }
actix-web = "2.0"
actix-rt = "1.0"
tokio = { version = "0.2", features = ["full"] }

# self project group
nature_common = {path = "../Nature-Common", version = "0.6.0"}
nature_db = {path = "../Nature-DB", features = ["mysql"], version = "0.6.0"}

[workspace]
members = ["../Nature-Common",
"../Nature-DB",
"../Nature-Retry",
"../Nature-Integrate-Test-Executor",
"../Nature-Demo",
"../Nature-Demo-Common",
"../Nature-Demo-Executor",
"../Nature-Demo-Executor-Restful",
]