[package]
name = "nature"
version = "0.0.1"
authors = ["XueBin Li"]
edition = "2018"

[dependencies]
# normal
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.0"
uuid = { version = "0.7", features = ["v3"] }
lru_time_cache = "0.8"

# for local converter implement
libloading = "0.5.0"

# log
log = "0.4.1"
fern = "0.5"        # Simple, efficient logging

#config
dotenv = "0.11"

# webup
rocket = "0.4"
rocket_contrib = "0.4"
#reqwest = "0.9"
actix-web = "0.7"

# self project group
nature_common = {path = "../Nature-Common"}
nature_db = {path = "../Nature-DB"}

# test
[dev-dependencies]
mockers_derive = "0.13"
mockers = "0.13"
nature_common = {path = "../Nature-Common"}
nature_db = {path = "../Nature-DB"}

[workspace]
members = ["../Nature-Common","../Nature-DB","../Nature-Retry","../Nature-integrate-test-converter"]